Hosts:
- IP: 10.42.56.96
  Hostname: ""
  OS: Linux - Ubuntu
- IP: 10.42.56.93
  Hostname: ""
  OS: Linux
SSH_CRED:
  ssh_user: ""
  ssh_pass: ""
Users:
- username: demouser13
  password: DemoPass0982
  group: users
