name: "Basic_Add_Users"
version: "2.1"
hosts:
{{- range .Hosts }}
  - "{{ .IP }}"
{{- end }}
vars:
  user_name: "new_admin"      # Change this value to set the username
  user_password: "P@ssw0rd"   # Change this value to set the password
tasks:
  - name: "Add user on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      echo "{{ env `EAGLE_SSH_PASS` }}" | sudo -S useradd -m -s /bin/bash "{{ .Vars.UserName }}"

  - name: "Add user on Windows systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      net user "{{ .Vars.UserName }}" "{{ .Vars.UserPassword }}" /add

  - name: "Verify user exists on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      id "{{ .Vars.UserName }}"
    register: user_exists
    ignore_errors: true

  - name: "Verify user exists on Windows systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      net user "{{ .Vars.UserName }}"
    register: user_exists
    ignore_errors: true

  - name: "Set password for user on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"] and user_exists.rc == 0
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      echo "{{ env `EAGLE_SSH_PASS` }}" | sudo -S bash -c "echo '{{ .Vars.UserName }}:{{ .Vars.UserPassword }}' | chpasswd"

settings:
  port: 22
