name: "Basic_Add_Users"
version: "2.1"
hosts:
{{- range .Hosts }}
  - "{{ .IP }}"
{{- end }}
vars:
  user_name: "{{ .Vars.UserName }}"
  user_password: "{{ .Vars.UserPassword }}"

tasks:
  - name: "Add user on Linux and Fedora systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "linux" or item.OS | lower contains "ubuntu" or item.OS | lower contains "fedora"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      if [ "$(whoami)" != "root" ]; then
        echo '{{ env `EAGLE_SSH_PASS` }}' | sudo -S useradd -m -s /bin/bash "{{ .Vars.UserName }}"
      else
        useradd -m -s /bin/bash "{{ .Vars.UserName }}"
      fi
    register: user_creation_result

  - name: "Set password for user on Linux and Fedora systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "linux" or item.OS | lower contains "ubuntu" or item.OS | lower contains "fedora"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      if id "{{ .Vars.UserName }}" &>/dev/null; then
        echo '{{ .Vars.UserName }}:{{ .Vars.UserPassword }}' | sudo chpasswd
      else
        echo "User does not exist, skipping password set"
      fi
    depends_on:
      - "Add user on Linux and Fedora systems"

  - name: "Add user on Windows systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      powershell -Command "& {net user \"{{ .Vars.UserName }}\" \"{{ .Vars.UserPassword }}\" /add}"
    register: windows_user_creation_result

settings:
  port: 22
