# File: add_user2.yaml

name: "add_user2"
version: "2.1"
#inventory: "inventory.yml"
hosts: []
  #- "192.168.56.101" #ubuntu machine

vars:
  new_user: "Samwise"
  new_password: "Pot@toes123"
  ssh_user: "{{ lookup('env','SSH_USER') }}"
  ssh_pass: "{{ lookup('env','SSH_PASS') }}"

tasks:

  - name: "Add user Samwise on Linux systems"
    ssh_user: "{{ ssh_user }}"
    ssh_password: "{{ ssh_pass }}"
    port: 22
    when: os_type.stdout in ["ubuntu", "fedora"]
    command: |
      echo "{{ ssh_pass }}" | sudo -S useradd -m -s /bin/bash Samwise

  - name: "Pause to ensure user creation"
    ssh_user: "{{ ssh_user }}"
    ssh_password: "{{ ssh_pass }}"
    port: 22
    command: sleep 2

  - name: "Verify user Samwise exists"
    ssh_user: "{{ ssh_user }}"
    ssh_password: "{{ ssh_pass }}"
    port: 22
    command: |
      echo "{{ ssh_pass }}" | sudo -S id samwise

  - name: "Set password for user Samwise on Linux systems"
    ssh_user: "{{ ssh_user }}"
    ssh_password: "{{ ssh_pass }}"
    port: 22
    when: os_type.stdout in ["ubuntu", "fedora"]
    command: |
      echo "{{ ssh_pass }}" | sudo -S bash -c "echo 'Samwise:Pot@toes123' | chpasswd"
settings:
   port: 22