name: "Basic_Add_Users"
version: "1.0"
hosts:
  - "192.168.70.43"
  - "192.168.70.44"
  - "192.168.70.46"
tasks:
  - name: "Debug SSH_PASSWORD"
    ssh_user: "${SSH_USERNAME}"
    ssh_password: "${SSH_PASSWORD}"
    command: 'echo "DEBUG: SSH_PASSWORD is ${SSH_PASSWORD}"'

  - name: "Validate sudo access"
    ssh_user: "${SSH_USERNAME}"
    ssh_password: "${SSH_PASSWORD}"
    command: 'echo "${SSH_PASSWORD}" | sudo -S echo "Sudo password is working"'

  - name: "Add user john on Linux systems"
    ssh_user: "${SSH_USERNAME}"
    ssh_password: "${SSH_PASSWORD}"
    when: os_type.stdout in ["ubuntu", "fedora"]
    command: |
      echo "${SSH_PASSWORD}" | sudo -S useradd -m -s /bin/bash john

  - name: "Set password for user john on Linux systems"
    ssh_user: "${SSH_USERNAME}"
    ssh_password: "${SSH_PASSWORD}"
    when: os_type.stdout in ["ubuntu", "fedora"]
    command: |
      echo "${SSH_PASSWORD}" | sudo -S bash -c "echo 'john:John123!' | chpasswd"

  
