name: "Basic_Add_Users"
version: "2.1"
hosts:
{{- range .Hosts }}
  - "{{ .IP }}"
{{- end }}
vars:
  user_name: "{{ .Vars.UserName }}"      # Use the passed username from inventory file
  user_password: "{{ .Vars.UserPassword }}"   # Use the passed password from inventory file
tasks:
  - name: "Add user on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu"]
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      echo "{{ env `EAGLE_SSH_PASS` }}" | sudo -S useradd -m -s /bin/bash "{{ .Vars.UserName }}"

  - name: "Add user on Fedora systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "fedora"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      echo "{{ env `EAGLE_SSH_PASS` }}" | sudo -S useradd -m -s /bin/bash "{{ .Vars.UserName }}"

  - name: "Add user on Windows systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      net user "{{ .Vars.UserName }}" "{{ .Vars.UserPassword }}" /add

  - name: "Set password for user on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      echo "{{ env `EAGLE_SSH_PASS` }}" | sudo -S bash -c "echo '{{ .Vars.UserName }}:{{ .Vars.UserPassword }}' | chpasswd"

settings:
  port: 22
