name: "Basic_Add_User"
version: "1.0"
hosts:
  - "192.168.70.43" #ubuntu1
  - "192.168.70.44" #ubuntu2
  - "192.168.70.46" #fedora
tasks:
  - name: "Add user on Linux systems"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    when: os_type.stdout in ["ubuntu", "fedora"]
    command: |
      echo 'What a nice day' | sudo -S useradd -m -s /bin/bash demo

  - name: "Set password for user on Linux systems"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    when: os_type.stdout in ["ubuntu", "fedora"]
    command: |
      echo 'What a nice day' | sudo -S bash -c "echo 'demo:securepassword' | chpasswd"

settings:
  port: 22
