name: "Basic_Add_Users"
version: "2.1"
hosts:
{{- range .Hosts }}
  - "{{ .IP }}"
{{- end }}
vars:
  user_name: "new_admin"      # Change this value to set the username
  user_password: "P@ssw0rd"   # Change this value to set the password
  eagle_user: "default_user"
  eagle_pass: "default_pass"
tasks:
  - name: "Add user on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      echo "{{ env `EAGLE_SSH_PASS` }}" | sudo -S useradd -m -s /bin/bash "{{ .vars.user_name }}"

  - name: "Add user on Windows systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      net user "{{ .Vars.UserName }}" "{{ .Vars.UserPassword }}" /add

  - name: "Add user on Linux"
    shell: |
      sudo useradd -m {{ eagle_user }}
      echo "{{ eagle_user }}:{{ eagle_pass }}" | sudo chpasswd
    when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

  - name: "Add user on Windows"
    shell: |
      net user {{ eagle_user }} {{ eagle_pass }} /add
      net localgroup Administrators {{ eagle_user }} /add
    when: ansible_os_family == "Windows"

  - name: "Pause to ensure user creation"
    command: sleep 2

  - name: "Verify user exists on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      id "{{ .Vars.UserName }}"
    register: user_exists
    ignore_errors: true

  - name: "Verify user exists on Windows systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: net user "{{ .Vars.UserName }}"
    register: user_exists
    ignore_errors: true

  - name: "Set password for user on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"] and user_exists.rc == 0
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      echo "{{ env `EAGLE_SSH_PASS` }}" | sudo -S bash -c "echo '{{ .Vars.UserName }}:{{ .Vars.UserPassword }}' | chpasswd"

  - name: "Set password for user on Windows systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "windows" and user_exists.rc == 0
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      net user "{{ .Vars.UserName }}" "{{ .Vars.UserPassword }}"

settings:
  port: 22
