# File: add_users.yaml
# Directory Path: /EagleDeploy_CLI/

name: "Basic_Add_Users"
version: "2.1"
hosts:
  - "192.168.70.43" # ubuntu1
  - "192.168.70.44" # ubuntu2
  - "192.168.70.46" # fedora
tasks:

  - name: "Add user john on Linux systems"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    when: os_type.stdout in ["ubuntu", "fedora"]
    command: |
      echo "What a nice day" | sudo -S useradd -m -s /bin/bash john

  - name: "Pause to ensure user creation"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: sleep 2

  - name: "Verify user john exists"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: |
      echo "What a nice day" | sudo -S id john

  - name: "Set password for user john on Linux systems"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    when: os_type.stdout in ["ubuntu", "fedora"]
    command: |
      echo "What a nice day" | sudo -S bash -c "echo 'john:ComplexP@ssw0rd!' | chpasswd"
settings:
   port: 22