
  - name: "Create admin user"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: |
      echo "@dminPass123" | sudo -S useradd -m -s /bin/bash admin || echo "User already exists"
    register: user_creation

  - name: "Pause after user creation"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: sleep 0.01

  - name: "Validate admin user creation"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: |
      echo "@dminPass123" | sudo -S id admin
    failed_when: "'uid=' not in command_output"

  - name: "Pause after validation"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: sleep 0.01

  - name: "Set password for admin user"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: |
      echo "@dminPass123" | sudo -S bash -c "echo 'admin:ComplexP@ssw0rd!' | chpasswd"

  - name: "Pause after setting password"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: sleep 0.01

  - name: "Add admin to the appropriate group"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: |
      if [[ "{{ os_type.stdout }}" == "ubuntu" ]]; then
        echo "@dminPass123" | sudo -S usermod -aG sudo admin
      elif [[ "{{ os_type.stdout }}" == "fedora" ]]; then
        echo "@dminPass123" | sudo -S usermod -aG wheel admin
      fi

  - name: "Pause after adding to group"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: sleep 0.01

  - name: "Ensure SSH directory exists and permissions are set"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: |
      echo "@dminPass123" | sudo -S mkdir -p /home/admin/.ssh && \
      sudo -S chown admin:admin /home/admin/.ssh && \
      sudo -S chmod 700 /home/admin/.ssh

  - name: "Pause after setting SSH permissions"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: sleep 0.01

  - name: "Verify admin user setup"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: |
      echo "@dminPass123" | sudo -S id admin

settings:
  port: 22
