name: "Enable AcceptEnv for SSH"
version: "1.2"
hosts:
  - "192.168.70.43"
  #- "192.168.70.44"
  #- "192.168.70.46"
tasks:
  - name: "Verify sudo access"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: |
      echo "What a nice day" | sudo -S echo "Sudo access works"

  - name: "Backup SSH configuration file"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: |
      echo "What a nice day" | sudo -S cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

  - name: "Add AcceptEnv for SSH_USERNAME and SSH_PASSWORD"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: |
      if ! echo "What a nice day" | sudo -S grep -q "^AcceptEnv SSH_USERNAME SSH_PASSWORD" /etc/ssh/sshd_config; then
        echo "What a nice day" | sudo -S bash -c "echo 'AcceptEnv SSH_USERNAME SSH_PASSWORD' >> /etc/ssh/sshd_config";
      else
        echo "AcceptEnv is already configured";
      fi

  - name: "Restart SSH service"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: |
      echo "What a nice day" | sudo -S systemctl restart sshd

  - name: "Pause for SSH service restart"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: sleep 2

  - name: "Verify AcceptEnv configuration"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: |
      echo "What a nice day" | sudo -S grep "^AcceptEnv SSH_USERNAME SSH_PASSWORD" /etc/ssh/sshd_config

  - name: "Debug sshd_config"
    ssh_user: "hunter"
    ssh_password: "What a nice day"
    port: 22
    command: |
      echo "What a nice day" | sudo -S cat /etc/ssh/sshd_config

settings:
  port: 22
