name: "List_Users_Playbook"
version: "1.0"
hosts:
  - "192.168.70.30" # ubuntu1
  - "192.168.70.32" # ubuntu2
  - "192.168.70.33" # fedora
tasks:
  - name: "List all users on the system"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    command: |
      awk -F: '$3 >= 1000 {print $1}' /etc/passwd
    register: users_output

  - name: "Log users output"
    debug:
      msg: "Users on {{ inventory_hostname }}: {{ users_output.stdout_lines }}"
settings:
  port: 22
