name: "List_Users_Playbook"
version: "1.1"
hosts:
{{- range .Hosts }}
  - "{{ .IP }}"
{{- end }}
tasks:
  - name: "List users on Linux systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd

  - name: "List users on Windows systems"
    ssh_user: "{{ env `EAGLE_SSH_USER` }}"
    ssh_password: "{{ env `EAGLE_SSH_PASS` }}"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "{{ .Hosts }}"
    loop_control:
      loop_var: item
    command: |
      net user | findstr /V "command completed successfully The following users"

settings:
  port: 22
