name: "List_Users_Playbook"
version: "1.1"
hosts:
tasks:
  - name: "List users on Linux systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "[]"
    loop_control:
      loop_var: item
    command: |
      awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd

  - name: "List users on Windows systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "[]"
    loop_control:
      loop_var: item
    command: |
      net user | findstr /V "command completed successfully The following users"

settings:
  port: 22
