name: "Basic_Add_Users"
version: "2.1"
hosts:
  - "10.42.56.101"
  - "10.42.56.100"
  - "10.42.56.102"
vars:
  user_name: "test_user01"      # Use the passed username from inventory file
  user_password: "tes123_pa12s#"   # Use the passed password from inventory file
tasks:
  - name: "Add user on Linux systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "[{10.42.56.101 node1-hunterpc Linux - Ubuntu 24.04} {10.42.56.100  Linux - Ubuntu 24.04} {10.42.56.102 Node_3 Windows 11 Pro}]"
    loop_control:
      loop_var: item
    command: |
      echo "@dminPass123" | sudo -S useradd -m -s /bin/bash "test_user01"

  - name: "Add user on Windows systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "[{10.42.56.101 node1-hunterpc Linux - Ubuntu 24.04} {10.42.56.100  Linux - Ubuntu 24.04} {10.42.56.102 Node_3 Windows 11 Pro}]"
    loop_control:
      loop_var: item
    command: |
      net user "test_user01" "tes123_pa12s#" /add

  - name: "Set password for user on Linux systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "[{10.42.56.101 node1-hunterpc Linux - Ubuntu 24.04} {10.42.56.100  Linux - Ubuntu 24.04} {10.42.56.102 Node_3 Windows 11 Pro}]"
    loop_control:
      loop_var: item
    command: |
      echo "@dminPass123" | sudo -S bash -c "echo 'test_user01:tes123_pa12s#' | chpasswd"

settings:
  port: 22
