name: "List_Users_Playbook"
version: "1.1"
hosts:
  - "10.42.56.106"
  - "10.42.56.103"
  - "10.42.56.98"
  - "10.42.56.110"
  - "10.42.56.115"
  - "10.42.56.99"
tasks:
  - name: "List users on Linux systems"
    ssh_user: ""
    ssh_password: ""
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "[{10.42.56.106 node-3-fedora Linux} {10.42.56.103 node-6-fedora Linux} {10.42.56.98 node-1-ubuntu Linux - Ubuntu} {10.42.56.110 node-4-win11 Windows} {10.42.56.115 node-5-win11 Windows} {10.42.56.99 node-2-ubuntu Linux - Ubuntu}]"
    loop_control:
      loop_var: item
    command: |
      awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd

  - name: "List users on Windows systems"
    ssh_user: ""
    ssh_password: ""
    port: 22
    when: item.OS | lower contains "windows"
    loop: "[{10.42.56.106 node-3-fedora Linux} {10.42.56.103 node-6-fedora Linux} {10.42.56.98 node-1-ubuntu Linux - Ubuntu} {10.42.56.110 node-4-win11 Windows} {10.42.56.115 node-5-win11 Windows} {10.42.56.99 node-2-ubuntu Linux - Ubuntu}]"
    loop_control:
      loop_var: item
    command: |
      net user | findstr /V "command completed successfully The following users"

settings:
  port: 22
