name: "Basic_Add_Users"
version: "2.1"
hosts:
  - "10.42.56.100"
  - "10.42.56.101"
  - "10.42.56.102"
vars:
  user_name: "new_admin"      # Change this value to set the username
  user_password: "P@ssw0rd"   # Change this value to set the password
tasks:
  - name: "Add user on Linux systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "[{10.42.56.100  Linux
} {10.42.56.101  Linux
} {10.42.56.102  
Microsoft Windows [Version 10.0.22631.4751]
}]"
    loop_control:
      loop_var: item
    command: |
      echo "@dminPass123" | sudo -S useradd -m -s /bin/bash ""

  - name: "Add user on Windows systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "[{10.42.56.100  Linux
} {10.42.56.101  Linux
} {10.42.56.102  
Microsoft Windows [Version 10.0.22631.4751]
}]"
    loop_control:
      loop_var: item
    command: |
      net user "" "" /add

  - name: "Verify user exists on Linux systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"]
    loop: "[{10.42.56.100  Linux
} {10.42.56.101  Linux
} {10.42.56.102  
Microsoft Windows [Version 10.0.22631.4751]
}]"
    loop_control:
      loop_var: item
    command: |
      id ""
    register: user_exists
    ignore_errors: true

  - name: "Verify user exists on Windows systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower contains "windows"
    loop: "[{10.42.56.100  Linux
} {10.42.56.101  Linux
} {10.42.56.102  
Microsoft Windows [Version 10.0.22631.4751]
}]"
    loop_control:
      loop_var: item
    command: |
      net user ""
    register: user_exists
    ignore_errors: true

  - name: "Set password for user on Linux systems"
    ssh_user: "eagleadmin"
    ssh_password: "@dminPass123"
    port: 22
    when: item.OS | lower in ["linux", "ubuntu", "fedora"] and user_exists.rc == 0
    loop: "[{10.42.56.100  Linux
} {10.42.56.101  Linux
} {10.42.56.102  
Microsoft Windows [Version 10.0.22631.4751]
}]"
    loop_control:
      loop_var: item
    command: |
      echo "@dminPass123" | sudo -S bash -c "echo ':' | chpasswd"

settings:
  port: 22
